// Auto-generated. Do not edit!

// (in-package work_smaart.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class goalPositionFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.NextMoveDirection = null;
    }
    else {
      if (initObj.hasOwnProperty('NextMoveDirection')) {
        this.NextMoveDirection = initObj.NextMoveDirection
      }
      else {
        this.NextMoveDirection = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type goalPositionFeedback
    // Serialize message field [NextMoveDirection]
    bufferOffset = _serializer.uint32(obj.NextMoveDirection, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type goalPositionFeedback
    let len;
    let data = new goalPositionFeedback(null);
    // Deserialize message field [NextMoveDirection]
    data.NextMoveDirection = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'work_smaart/goalPositionFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd83087dbb64ce5212281da01fb5b9627';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #define a feedback message
    uint32 NextMoveDirection # 0=N (norte), 1=E (leste), 2=S (sul), 3=W (oeste)
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new goalPositionFeedback(null);
    if (msg.NextMoveDirection !== undefined) {
      resolved.NextMoveDirection = msg.NextMoveDirection;
    }
    else {
      resolved.NextMoveDirection = 0
    }

    return resolved;
    }
};

module.exports = goalPositionFeedback;
