// Auto-generated. Do not edit!

// (in-package work_smaart.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class goalPositionResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.GoBaseOrFinalGoal = null;
    }
    else {
      if (initObj.hasOwnProperty('GoBaseOrFinalGoal')) {
        this.GoBaseOrFinalGoal = initObj.GoBaseOrFinalGoal
      }
      else {
        this.GoBaseOrFinalGoal = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type goalPositionResult
    // Serialize message field [GoBaseOrFinalGoal]
    bufferOffset = _serializer.uint32(obj.GoBaseOrFinalGoal, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type goalPositionResult
    let len;
    let data = new goalPositionResult(null);
    // Deserialize message field [GoBaseOrFinalGoal]
    data.GoBaseOrFinalGoal = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'work_smaart/goalPositionResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'c91f88dea877ef4ffe805fa3d41d777f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #define the result
    uint32 GoBaseOrFinalGoal
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new goalPositionResult(null);
    if (msg.GoBaseOrFinalGoal !== undefined) {
      resolved.GoBaseOrFinalGoal = msg.GoBaseOrFinalGoal;
    }
    else {
      resolved.GoBaseOrFinalGoal = 0
    }

    return resolved;
    }
};

module.exports = goalPositionResult;
