(cl:defpackage work_smaart-msg
  (:use )
  (:export
   "<BOOLS>"
   "BOOLS"
   "<GOAL>"
   "GOAL"
   "<NUM>"
   "NUM"
   "<POINT32>"
   "POINT32"
   "<GOALPOSITIONACTION>"
   "GOALPOSITIONACTION"
   "<GOALPOSITIONACTIONFEEDBACK>"
   "GOALPOSITIONACTIONFEEDBACK"
   "<GOALPOSITIONACTIONGOAL>"
   "GOALPOSITIONACTIONGOAL"
   "<GOALPOSITIONACTIONRESULT>"
   "GOALPOSITIONACTIONRESULT"
   "<GOALPOSITIONFEEDBACK>"
   "GOALPOSITIONFEEDBACK"
   "<GOALPOSITIONGOAL>"
   "GOALPOSITIONGOAL"
   "<GOALPOSITIONRESULT>"
   "GOALPOSITIONRESULT"
  ))

