; Auto-generated. Do not edit!


(cl:in-package work_smaart-msg)


;//! \htmlinclude goalPositionResult.msg.html

(cl:defclass <goalPositionResult> (roslisp-msg-protocol:ros-message)
  ((GoBaseOrFinalGoal
    :reader GoBaseOrFinalGoal
    :initarg :GoBaseOrFinalGoal
    :type cl:integer
    :initform 0))
)

(cl:defclass goalPositionResult (<goalPositionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <goalPositionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'goalPositionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name work_smaart-msg:<goalPositionResult> is deprecated: use work_smaart-msg:goalPositionResult instead.")))

(cl:ensure-generic-function 'GoBaseOrFinalGoal-val :lambda-list '(m))
(cl:defmethod GoBaseOrFinalGoal-val ((m <goalPositionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader work_smaart-msg:GoBaseOrFinalGoal-val is deprecated.  Use work_smaart-msg:GoBaseOrFinalGoal instead.")
  (GoBaseOrFinalGoal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <goalPositionResult>) ostream)
  "Serializes a message object of type '<goalPositionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'GoBaseOrFinalGoal)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'GoBaseOrFinalGoal)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'GoBaseOrFinalGoal)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'GoBaseOrFinalGoal)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <goalPositionResult>) istream)
  "Deserializes a message object of type '<goalPositionResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'GoBaseOrFinalGoal)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'GoBaseOrFinalGoal)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'GoBaseOrFinalGoal)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'GoBaseOrFinalGoal)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<goalPositionResult>)))
  "Returns string type for a message object of type '<goalPositionResult>"
  "work_smaart/goalPositionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'goalPositionResult)))
  "Returns string type for a message object of type 'goalPositionResult"
  "work_smaart/goalPositionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<goalPositionResult>)))
  "Returns md5sum for a message object of type '<goalPositionResult>"
  "c91f88dea877ef4ffe805fa3d41d777f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'goalPositionResult)))
  "Returns md5sum for a message object of type 'goalPositionResult"
  "c91f88dea877ef4ffe805fa3d41d777f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<goalPositionResult>)))
  "Returns full string definition for message of type '<goalPositionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#define the result~%uint32 GoBaseOrFinalGoal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'goalPositionResult)))
  "Returns full string definition for message of type 'goalPositionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#define the result~%uint32 GoBaseOrFinalGoal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <goalPositionResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <goalPositionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'goalPositionResult
    (cl:cons ':GoBaseOrFinalGoal (GoBaseOrFinalGoal msg))
))
