; Auto-generated. Do not edit!


(cl:in-package work_smaart-msg)


;//! \htmlinclude goalPositionGoal.msg.html

(cl:defclass <goalPositionGoal> (roslisp-msg-protocol:ros-message)
  ((EndOfBoard
    :reader EndOfBoard
    :initarg :EndOfBoard
    :type geometry_msgs-msg:Point
    :initform (cl:make-instance 'geometry_msgs-msg:Point))
   (StartOfBoard
    :reader StartOfBoard
    :initarg :StartOfBoard
    :type geometry_msgs-msg:Point
    :initform (cl:make-instance 'geometry_msgs-msg:Point)))
)

(cl:defclass goalPositionGoal (<goalPositionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <goalPositionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'goalPositionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name work_smaart-msg:<goalPositionGoal> is deprecated: use work_smaart-msg:goalPositionGoal instead.")))

(cl:ensure-generic-function 'EndOfBoard-val :lambda-list '(m))
(cl:defmethod EndOfBoard-val ((m <goalPositionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader work_smaart-msg:EndOfBoard-val is deprecated.  Use work_smaart-msg:EndOfBoard instead.")
  (EndOfBoard m))

(cl:ensure-generic-function 'StartOfBoard-val :lambda-list '(m))
(cl:defmethod StartOfBoard-val ((m <goalPositionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader work_smaart-msg:StartOfBoard-val is deprecated.  Use work_smaart-msg:StartOfBoard instead.")
  (StartOfBoard m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <goalPositionGoal>) ostream)
  "Serializes a message object of type '<goalPositionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'EndOfBoard) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'StartOfBoard) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <goalPositionGoal>) istream)
  "Deserializes a message object of type '<goalPositionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'EndOfBoard) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'StartOfBoard) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<goalPositionGoal>)))
  "Returns string type for a message object of type '<goalPositionGoal>"
  "work_smaart/goalPositionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'goalPositionGoal)))
  "Returns string type for a message object of type 'goalPositionGoal"
  "work_smaart/goalPositionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<goalPositionGoal>)))
  "Returns md5sum for a message object of type '<goalPositionGoal>"
  "af8cb2ee93bf43582cce3a6b78454de8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'goalPositionGoal)))
  "Returns md5sum for a message object of type 'goalPositionGoal"
  "af8cb2ee93bf43582cce3a6b78454de8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<goalPositionGoal>)))
  "Returns full string definition for message of type '<goalPositionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#define the goal~%geometry_msgs/Point EndOfBoard~%geometry_msgs/Point StartOfBoard~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'goalPositionGoal)))
  "Returns full string definition for message of type 'goalPositionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#define the goal~%geometry_msgs/Point EndOfBoard~%geometry_msgs/Point StartOfBoard~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <goalPositionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'EndOfBoard))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'StartOfBoard))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <goalPositionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'goalPositionGoal
    (cl:cons ':EndOfBoard (EndOfBoard msg))
    (cl:cons ':StartOfBoard (StartOfBoard msg))
))
