; Auto-generated. Do not edit!


(cl:in-package work_smaart-msg)


;//! \htmlinclude goalPositionFeedback.msg.html

(cl:defclass <goalPositionFeedback> (roslisp-msg-protocol:ros-message)
  ((NextMoveDirection
    :reader NextMoveDirection
    :initarg :NextMoveDirection
    :type cl:integer
    :initform 0))
)

(cl:defclass goalPositionFeedback (<goalPositionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <goalPositionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'goalPositionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name work_smaart-msg:<goalPositionFeedback> is deprecated: use work_smaart-msg:goalPositionFeedback instead.")))

(cl:ensure-generic-function 'NextMoveDirection-val :lambda-list '(m))
(cl:defmethod NextMoveDirection-val ((m <goalPositionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader work_smaart-msg:NextMoveDirection-val is deprecated.  Use work_smaart-msg:NextMoveDirection instead.")
  (NextMoveDirection m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <goalPositionFeedback>) ostream)
  "Serializes a message object of type '<goalPositionFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'NextMoveDirection)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'NextMoveDirection)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'NextMoveDirection)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'NextMoveDirection)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <goalPositionFeedback>) istream)
  "Deserializes a message object of type '<goalPositionFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'NextMoveDirection)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'NextMoveDirection)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'NextMoveDirection)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'NextMoveDirection)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<goalPositionFeedback>)))
  "Returns string type for a message object of type '<goalPositionFeedback>"
  "work_smaart/goalPositionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'goalPositionFeedback)))
  "Returns string type for a message object of type 'goalPositionFeedback"
  "work_smaart/goalPositionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<goalPositionFeedback>)))
  "Returns md5sum for a message object of type '<goalPositionFeedback>"
  "d83087dbb64ce5212281da01fb5b9627")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'goalPositionFeedback)))
  "Returns md5sum for a message object of type 'goalPositionFeedback"
  "d83087dbb64ce5212281da01fb5b9627")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<goalPositionFeedback>)))
  "Returns full string definition for message of type '<goalPositionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#define a feedback message~%uint32 NextMoveDirection # 0=N (norte), 1=E (leste), 2=S (sul), 3=W (oeste)~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'goalPositionFeedback)))
  "Returns full string definition for message of type 'goalPositionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#define a feedback message~%uint32 NextMoveDirection # 0=N (norte), 1=E (leste), 2=S (sul), 3=W (oeste)~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <goalPositionFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <goalPositionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'goalPositionFeedback
    (cl:cons ':NextMoveDirection (NextMoveDirection msg))
))
