// Generated by gencpp from file work_smaart/BatCalcResponse.msg
// DO NOT EDIT!


#ifndef WORK_SMAART_MESSAGE_BATCALCRESPONSE_H
#define WORK_SMAART_MESSAGE_BATCALCRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace work_smaart
{
template <class ContainerAllocator>
struct BatCalcResponse_
{
  typedef BatCalcResponse_<ContainerAllocator> Type;

  BatCalcResponse_()
    : isWeak(false)  {
    }
  BatCalcResponse_(const ContainerAllocator& _alloc)
    : isWeak(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isWeak_type;
  _isWeak_type isWeak;





  typedef boost::shared_ptr< ::work_smaart::BatCalcResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::work_smaart::BatCalcResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BatCalcResponse_

typedef ::work_smaart::BatCalcResponse_<std::allocator<void> > BatCalcResponse;

typedef boost::shared_ptr< ::work_smaart::BatCalcResponse > BatCalcResponsePtr;
typedef boost::shared_ptr< ::work_smaart::BatCalcResponse const> BatCalcResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::work_smaart::BatCalcResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::work_smaart::BatCalcResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::work_smaart::BatCalcResponse_<ContainerAllocator1> & lhs, const ::work_smaart::BatCalcResponse_<ContainerAllocator2> & rhs)
{
  return lhs.isWeak == rhs.isWeak;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::work_smaart::BatCalcResponse_<ContainerAllocator1> & lhs, const ::work_smaart::BatCalcResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace work_smaart

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::work_smaart::BatCalcResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::work_smaart::BatCalcResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::work_smaart::BatCalcResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::work_smaart::BatCalcResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::work_smaart::BatCalcResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::work_smaart::BatCalcResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::work_smaart::BatCalcResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "902658ae4fcb9d45c767db4811cab8bd";
  }

  static const char* value(const ::work_smaart::BatCalcResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x902658ae4fcb9d45ULL;
  static const uint64_t static_value2 = 0xc767db4811cab8bdULL;
};

template<class ContainerAllocator>
struct DataType< ::work_smaart::BatCalcResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "work_smaart/BatCalcResponse";
  }

  static const char* value(const ::work_smaart::BatCalcResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::work_smaart::BatCalcResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isWeak\n"
"\n"
;
  }

  static const char* value(const ::work_smaart::BatCalcResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::work_smaart::BatCalcResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isWeak);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BatCalcResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::work_smaart::BatCalcResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::work_smaart::BatCalcResponse_<ContainerAllocator>& v)
  {
    s << indent << "isWeak: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isWeak);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WORK_SMAART_MESSAGE_BATCALCRESPONSE_H
