// Generated by gencpp from file work_smaart/goalPositionResult.msg
// DO NOT EDIT!


#ifndef WORK_SMAART_MESSAGE_GOALPOSITIONRESULT_H
#define WORK_SMAART_MESSAGE_GOALPOSITIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace work_smaart
{
template <class ContainerAllocator>
struct goalPositionResult_
{
  typedef goalPositionResult_<ContainerAllocator> Type;

  goalPositionResult_()
    : GoBaseOrFinalGoal(0)  {
    }
  goalPositionResult_(const ContainerAllocator& _alloc)
    : GoBaseOrFinalGoal(0)  {
  (void)_alloc;
    }



   typedef uint32_t _GoBaseOrFinalGoal_type;
  _GoBaseOrFinalGoal_type GoBaseOrFinalGoal;





  typedef boost::shared_ptr< ::work_smaart::goalPositionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::work_smaart::goalPositionResult_<ContainerAllocator> const> ConstPtr;

}; // struct goalPositionResult_

typedef ::work_smaart::goalPositionResult_<std::allocator<void> > goalPositionResult;

typedef boost::shared_ptr< ::work_smaart::goalPositionResult > goalPositionResultPtr;
typedef boost::shared_ptr< ::work_smaart::goalPositionResult const> goalPositionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::work_smaart::goalPositionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::work_smaart::goalPositionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::work_smaart::goalPositionResult_<ContainerAllocator1> & lhs, const ::work_smaart::goalPositionResult_<ContainerAllocator2> & rhs)
{
  return lhs.GoBaseOrFinalGoal == rhs.GoBaseOrFinalGoal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::work_smaart::goalPositionResult_<ContainerAllocator1> & lhs, const ::work_smaart::goalPositionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace work_smaart

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::work_smaart::goalPositionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::work_smaart::goalPositionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::work_smaart::goalPositionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::work_smaart::goalPositionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::work_smaart::goalPositionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::work_smaart::goalPositionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::work_smaart::goalPositionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c91f88dea877ef4ffe805fa3d41d777f";
  }

  static const char* value(const ::work_smaart::goalPositionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc91f88dea877ef4fULL;
  static const uint64_t static_value2 = 0xfe805fa3d41d777fULL;
};

template<class ContainerAllocator>
struct DataType< ::work_smaart::goalPositionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "work_smaart/goalPositionResult";
  }

  static const char* value(const ::work_smaart::goalPositionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::work_smaart::goalPositionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#define the result\n"
"uint32 GoBaseOrFinalGoal\n"
;
  }

  static const char* value(const ::work_smaart::goalPositionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::work_smaart::goalPositionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.GoBaseOrFinalGoal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goalPositionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::work_smaart::goalPositionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::work_smaart::goalPositionResult_<ContainerAllocator>& v)
  {
    s << indent << "GoBaseOrFinalGoal: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.GoBaseOrFinalGoal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WORK_SMAART_MESSAGE_GOALPOSITIONRESULT_H
