// Generated by gencpp from file work_smaart/goalPositionFeedback.msg
// DO NOT EDIT!


#ifndef WORK_SMAART_MESSAGE_GOALPOSITIONFEEDBACK_H
#define WORK_SMAART_MESSAGE_GOALPOSITIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace work_smaart
{
template <class ContainerAllocator>
struct goalPositionFeedback_
{
  typedef goalPositionFeedback_<ContainerAllocator> Type;

  goalPositionFeedback_()
    : NextMoveDirection(0)  {
    }
  goalPositionFeedback_(const ContainerAllocator& _alloc)
    : NextMoveDirection(0)  {
  (void)_alloc;
    }



   typedef uint32_t _NextMoveDirection_type;
  _NextMoveDirection_type NextMoveDirection;





  typedef boost::shared_ptr< ::work_smaart::goalPositionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::work_smaart::goalPositionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct goalPositionFeedback_

typedef ::work_smaart::goalPositionFeedback_<std::allocator<void> > goalPositionFeedback;

typedef boost::shared_ptr< ::work_smaart::goalPositionFeedback > goalPositionFeedbackPtr;
typedef boost::shared_ptr< ::work_smaart::goalPositionFeedback const> goalPositionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::work_smaart::goalPositionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::work_smaart::goalPositionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::work_smaart::goalPositionFeedback_<ContainerAllocator1> & lhs, const ::work_smaart::goalPositionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.NextMoveDirection == rhs.NextMoveDirection;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::work_smaart::goalPositionFeedback_<ContainerAllocator1> & lhs, const ::work_smaart::goalPositionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace work_smaart

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::work_smaart::goalPositionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::work_smaart::goalPositionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::work_smaart::goalPositionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::work_smaart::goalPositionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::work_smaart::goalPositionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::work_smaart::goalPositionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::work_smaart::goalPositionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d83087dbb64ce5212281da01fb5b9627";
  }

  static const char* value(const ::work_smaart::goalPositionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd83087dbb64ce521ULL;
  static const uint64_t static_value2 = 0x2281da01fb5b9627ULL;
};

template<class ContainerAllocator>
struct DataType< ::work_smaart::goalPositionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "work_smaart/goalPositionFeedback";
  }

  static const char* value(const ::work_smaart::goalPositionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::work_smaart::goalPositionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#define a feedback message\n"
"uint32 NextMoveDirection # 0=N (norte), 1=E (leste), 2=S (sul), 3=W (oeste)\n"
;
  }

  static const char* value(const ::work_smaart::goalPositionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::work_smaart::goalPositionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.NextMoveDirection);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goalPositionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::work_smaart::goalPositionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::work_smaart::goalPositionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "NextMoveDirection: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.NextMoveDirection);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WORK_SMAART_MESSAGE_GOALPOSITIONFEEDBACK_H
