// Generated by gencpp from file work_smaart/goalPositionGoal.msg
// DO NOT EDIT!


#ifndef WORK_SMAART_MESSAGE_GOALPOSITIONGOAL_H
#define WORK_SMAART_MESSAGE_GOALPOSITIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace work_smaart
{
template <class ContainerAllocator>
struct goalPositionGoal_
{
  typedef goalPositionGoal_<ContainerAllocator> Type;

  goalPositionGoal_()
    : EndOfBoard()
    , StartOfBoard()  {
    }
  goalPositionGoal_(const ContainerAllocator& _alloc)
    : EndOfBoard(_alloc)
    , StartOfBoard(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _EndOfBoard_type;
  _EndOfBoard_type EndOfBoard;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _StartOfBoard_type;
  _StartOfBoard_type StartOfBoard;





  typedef boost::shared_ptr< ::work_smaart::goalPositionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::work_smaart::goalPositionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct goalPositionGoal_

typedef ::work_smaart::goalPositionGoal_<std::allocator<void> > goalPositionGoal;

typedef boost::shared_ptr< ::work_smaart::goalPositionGoal > goalPositionGoalPtr;
typedef boost::shared_ptr< ::work_smaart::goalPositionGoal const> goalPositionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::work_smaart::goalPositionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::work_smaart::goalPositionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::work_smaart::goalPositionGoal_<ContainerAllocator1> & lhs, const ::work_smaart::goalPositionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.EndOfBoard == rhs.EndOfBoard &&
    lhs.StartOfBoard == rhs.StartOfBoard;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::work_smaart::goalPositionGoal_<ContainerAllocator1> & lhs, const ::work_smaart::goalPositionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace work_smaart

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::work_smaart::goalPositionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::work_smaart::goalPositionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::work_smaart::goalPositionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::work_smaart::goalPositionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::work_smaart::goalPositionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::work_smaart::goalPositionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::work_smaart::goalPositionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af8cb2ee93bf43582cce3a6b78454de8";
  }

  static const char* value(const ::work_smaart::goalPositionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf8cb2ee93bf4358ULL;
  static const uint64_t static_value2 = 0x2cce3a6b78454de8ULL;
};

template<class ContainerAllocator>
struct DataType< ::work_smaart::goalPositionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "work_smaart/goalPositionGoal";
  }

  static const char* value(const ::work_smaart::goalPositionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::work_smaart::goalPositionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#define the goal\n"
"geometry_msgs/Point EndOfBoard\n"
"geometry_msgs/Point StartOfBoard\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::work_smaart::goalPositionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::work_smaart::goalPositionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.EndOfBoard);
      stream.next(m.StartOfBoard);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goalPositionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::work_smaart::goalPositionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::work_smaart::goalPositionGoal_<ContainerAllocator>& v)
  {
    s << indent << "EndOfBoard: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.EndOfBoard);
    s << indent << "StartOfBoard: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.StartOfBoard);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WORK_SMAART_MESSAGE_GOALPOSITIONGOAL_H
