// Generated by gencpp from file work_smaart/isGoalResponse.msg
// DO NOT EDIT!


#ifndef WORK_SMAART_MESSAGE_ISGOALRESPONSE_H
#define WORK_SMAART_MESSAGE_ISGOALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace work_smaart
{
template <class ContainerAllocator>
struct isGoalResponse_
{
  typedef isGoalResponse_<ContainerAllocator> Type;

  isGoalResponse_()
    : isGoal(false)  {
    }
  isGoalResponse_(const ContainerAllocator& _alloc)
    : isGoal(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isGoal_type;
  _isGoal_type isGoal;





  typedef boost::shared_ptr< ::work_smaart::isGoalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::work_smaart::isGoalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct isGoalResponse_

typedef ::work_smaart::isGoalResponse_<std::allocator<void> > isGoalResponse;

typedef boost::shared_ptr< ::work_smaart::isGoalResponse > isGoalResponsePtr;
typedef boost::shared_ptr< ::work_smaart::isGoalResponse const> isGoalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::work_smaart::isGoalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::work_smaart::isGoalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::work_smaart::isGoalResponse_<ContainerAllocator1> & lhs, const ::work_smaart::isGoalResponse_<ContainerAllocator2> & rhs)
{
  return lhs.isGoal == rhs.isGoal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::work_smaart::isGoalResponse_<ContainerAllocator1> & lhs, const ::work_smaart::isGoalResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace work_smaart

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::work_smaart::isGoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::work_smaart::isGoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::work_smaart::isGoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::work_smaart::isGoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::work_smaart::isGoalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::work_smaart::isGoalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::work_smaart::isGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85c7050503eb5c86b628eb1d677c0575";
  }

  static const char* value(const ::work_smaart::isGoalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85c7050503eb5c86ULL;
  static const uint64_t static_value2 = 0xb628eb1d677c0575ULL;
};

template<class ContainerAllocator>
struct DataType< ::work_smaart::isGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "work_smaart/isGoalResponse";
  }

  static const char* value(const ::work_smaart::isGoalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::work_smaart::isGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isGoal\n"
;
  }

  static const char* value(const ::work_smaart::isGoalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::work_smaart::isGoalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isGoal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct isGoalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::work_smaart::isGoalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::work_smaart::isGoalResponse_<ContainerAllocator>& v)
  {
    s << indent << "isGoal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isGoal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WORK_SMAART_MESSAGE_ISGOALRESPONSE_H
