// Generated by gencpp from file work_smaart/isGoal.msg
// DO NOT EDIT!


#ifndef WORK_SMAART_MESSAGE_ISGOAL_H
#define WORK_SMAART_MESSAGE_ISGOAL_H

#include <ros/service_traits.h>


#include <work_smaart/isGoalRequest.h>
#include <work_smaart/isGoalResponse.h>


namespace work_smaart
{

struct isGoal
{

typedef isGoalRequest Request;
typedef isGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct isGoal
} // namespace work_smaart


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::work_smaart::isGoal > {
  static const char* value()
  {
    return "1b7b9b83759f54d801ad41a9a10d9074";
  }

  static const char* value(const ::work_smaart::isGoal&) { return value(); }
};

template<>
struct DataType< ::work_smaart::isGoal > {
  static const char* value()
  {
    return "work_smaart/isGoal";
  }

  static const char* value(const ::work_smaart::isGoal&) { return value(); }
};


// service_traits::MD5Sum< ::work_smaart::isGoalRequest> should match
// service_traits::MD5Sum< ::work_smaart::isGoal >
template<>
struct MD5Sum< ::work_smaart::isGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::work_smaart::isGoal >::value();
  }
  static const char* value(const ::work_smaart::isGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::work_smaart::isGoalRequest> should match
// service_traits::DataType< ::work_smaart::isGoal >
template<>
struct DataType< ::work_smaart::isGoalRequest>
{
  static const char* value()
  {
    return DataType< ::work_smaart::isGoal >::value();
  }
  static const char* value(const ::work_smaart::isGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::work_smaart::isGoalResponse> should match
// service_traits::MD5Sum< ::work_smaart::isGoal >
template<>
struct MD5Sum< ::work_smaart::isGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::work_smaart::isGoal >::value();
  }
  static const char* value(const ::work_smaart::isGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::work_smaart::isGoalResponse> should match
// service_traits::DataType< ::work_smaart::isGoal >
template<>
struct DataType< ::work_smaart::isGoalResponse>
{
  static const char* value()
  {
    return DataType< ::work_smaart::isGoal >::value();
  }
  static const char* value(const ::work_smaart::isGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WORK_SMAART_MESSAGE_ISGOAL_H
