// Generated by gencpp from file work_smaart/Num.msg
// DO NOT EDIT!


#ifndef WORK_SMAART_MESSAGE_NUM_H
#define WORK_SMAART_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace work_smaart
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : dist(0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : dist(0)  {
  (void)_alloc;
    }



   typedef int64_t _dist_type;
  _dist_type dist;





  typedef boost::shared_ptr< ::work_smaart::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::work_smaart::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::work_smaart::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::work_smaart::Num > NumPtr;
typedef boost::shared_ptr< ::work_smaart::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::work_smaart::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::work_smaart::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::work_smaart::Num_<ContainerAllocator1> & lhs, const ::work_smaart::Num_<ContainerAllocator2> & rhs)
{
  return lhs.dist == rhs.dist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::work_smaart::Num_<ContainerAllocator1> & lhs, const ::work_smaart::Num_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace work_smaart

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::work_smaart::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::work_smaart::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::work_smaart::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::work_smaart::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::work_smaart::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::work_smaart::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::work_smaart::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1177a5a6d683bdd440563d77ed5b58d";
  }

  static const char* value(const ::work_smaart::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1177a5a6d683bddULL;
  static const uint64_t static_value2 = 0x440563d77ed5b58dULL;
};

template<class ContainerAllocator>
struct DataType< ::work_smaart::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "work_smaart/Num";
  }

  static const char* value(const ::work_smaart::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::work_smaart::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 dist\n"
;
  }

  static const char* value(const ::work_smaart::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::work_smaart::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::work_smaart::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::work_smaart::Num_<ContainerAllocator>& v)
  {
    s << indent << "dist: ";
    Printer<int64_t>::stream(s, indent + "  ", v.dist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WORK_SMAART_MESSAGE_NUM_H
