// Generated by gencpp from file work_smaart/Point32.msg
// DO NOT EDIT!


#ifndef WORK_SMAART_MESSAGE_POINT32_H
#define WORK_SMAART_MESSAGE_POINT32_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point32.h>

namespace work_smaart
{
template <class ContainerAllocator>
struct Point32_
{
  typedef Point32_<ContainerAllocator> Type;

  Point32_()
    : posicao()  {
    }
  Point32_(const ContainerAllocator& _alloc)
    : posicao(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point32_<ContainerAllocator>  _posicao_type;
  _posicao_type posicao;





  typedef boost::shared_ptr< ::work_smaart::Point32_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::work_smaart::Point32_<ContainerAllocator> const> ConstPtr;

}; // struct Point32_

typedef ::work_smaart::Point32_<std::allocator<void> > Point32;

typedef boost::shared_ptr< ::work_smaart::Point32 > Point32Ptr;
typedef boost::shared_ptr< ::work_smaart::Point32 const> Point32ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::work_smaart::Point32_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::work_smaart::Point32_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::work_smaart::Point32_<ContainerAllocator1> & lhs, const ::work_smaart::Point32_<ContainerAllocator2> & rhs)
{
  return lhs.posicao == rhs.posicao;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::work_smaart::Point32_<ContainerAllocator1> & lhs, const ::work_smaart::Point32_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace work_smaart

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::work_smaart::Point32_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::work_smaart::Point32_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::work_smaart::Point32_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::work_smaart::Point32_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::work_smaart::Point32_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::work_smaart::Point32_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::work_smaart::Point32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8346df72a1510091ffcefeb2f51167a7";
  }

  static const char* value(const ::work_smaart::Point32_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8346df72a1510091ULL;
  static const uint64_t static_value2 = 0xffcefeb2f51167a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::work_smaart::Point32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "work_smaart/Point32";
  }

  static const char* value(const ::work_smaart::Point32_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::work_smaart::Point32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point32 posicao\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::work_smaart::Point32_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::work_smaart::Point32_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.posicao);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Point32_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::work_smaart::Point32_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::work_smaart::Point32_<ContainerAllocator>& v)
  {
    s << indent << "posicao: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "  ", v.posicao);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WORK_SMAART_MESSAGE_POINT32_H
